-- ============================================================
-- Reportes del Excel que NO están en hseq_12_03_2026.sql
-- Generado: 2026-03-12 16:21:19
-- Total de inserciones: 37
-- ============================================================

SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';
START TRANSACTION;
SET NAMES utf8mb4;

-- Reporte 128 - hallazgos (Pedro Rafael Cadena Ordoñez)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(128, 36, NULL, NULL, 'hallazgos', NULL, 'Áreas Seguras', NULL, '2026-01-02', 'pozos', '', 'accion_mejoramiento', 'Realizó safety tour al finalizar la intervención en PSB1, se solicita limpieza del well pad por parte del aliado CT-Halliburton y se realiza la entrega de pozo dejando locación en buenas condiciones de orden y aseo.', 'Realizo limpieza del well pad por parte del aliado CT-Halliburton.', 'cerrada', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'aprobado', NULL, NULL, NULL, '2026-01-12 00:00:00', '2026-01-12 00:00:00');

-- Reporte 129 - conversaciones (Pedro Rafael Cadena Ordoñez)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(129, 36, NULL, NULL, 'conversaciones', NULL, 'Charlas de seguridad', NULL, '2026-01-03', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'reflexion', 'PSB1', 'pozos', '', 'Realizó Charla de seguridad con personal aliado en locación PSB1. dirige reunión de seguridad con cada una de las empresas aliadas, firma permisos de trabajo (Turno día).  Comparte campaña: “seguridad vial”', 'Charlas de seguridad', 'aprobado', NULL, NULL, NULL, '2026-01-12 00:00:00', '2026-01-12 00:00:00');

-- Reporte 130 - conversaciones (Pedro Rafael Cadena Ordoñez)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(130, 36, NULL, NULL, 'conversaciones', NULL, 'Áreas Seguras', NULL, '2026-01-05', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'reflexion', 'FRAP13', 'pozos', '', 'Realizó Charla de seguridad con personal aliado en locación FRAP13. dirige reunión de seguridad con cada una de las empresas aliadas, revisa y divulga análisis de riesgos y firma permisos de trabajo (Turno día).  Comparte campaña: “inicio de operaciones seguras.”', 'Áreas Seguras', 'aprobado', NULL, NULL, NULL, '2026-01-12 00:00:00', '2026-01-12 00:00:00');

-- Reporte 131 - hallazgos (Pedro Rafael Cadena Ordoñez)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(131, 36, NULL, NULL, 'hallazgos', NULL, 'Áreas Seguras', NULL, '2026-01-05', 'pozos', '', 'accion_mejoramiento', 'Realizó safety tour al inicio de la intervención en FRAP13, encontrando buenas condiciones de orden y aseo. Verifico el cierre de los hallazgos encontrados en la visita previa (desmonte de DFL, pararrayos y jaula protectora) y recibe locación por parte de operaciones de superficie.', 'Realizo desmonte de DFL, pararrayos y jaula protectora y recibió pozo.', 'cerrada', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'aprobado', NULL, NULL, NULL, '2026-01-12 00:00:00', '2026-01-12 00:00:00');

-- Reporte 132 - conversaciones (Pedro Rafael Cadena Ordoñez)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(132, 36, NULL, NULL, 'conversaciones', NULL, 'Charlas de seguridad', NULL, '2026-01-06', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'conversacion', 'FRAP13', 'pozos', '', 'Realizó Charla de seguridad con personal aliado en locación FRAP13. dirige reunión de seguridad con cada una de las empresas aliadas. Divulga Alerta HSE: “Golpe en hombro izquierdo a trabajador.”', 'Charlas de seguridad', 'aprobado', NULL, NULL, NULL, '2026-01-12 00:00:00', '2026-01-12 00:00:00');

-- Reporte 133 - conversaciones (Pedro Rafael Cadena Ordoñez)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(133, 36, NULL, NULL, 'conversaciones', NULL, 'Charlas de seguridad', NULL, '2026-01-07', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'conversacion', 'FRAP13', 'pozos', '', 'Realizó Charla de seguridad con personal aliado en locación FRAP13. dirige reunión de seguridad con cada una de las empresas aliadas. Divulga Alerta HSE: “Perdida de contención en pozo durante intervención.”', 'Charlas de seguridad', 'aprobado', NULL, NULL, NULL, '2026-01-12 00:00:00', '2026-01-12 00:00:00');

-- Reporte 134 - conversaciones (Pedro Rafael Cadena Ordoñez)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(134, 36, NULL, NULL, 'conversaciones', NULL, 'Charlas de seguridad', NULL, '2026-01-08', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'conversacion', 'FRAP13', 'pozos', '', 'Realizó Charla de seguridad con personal aliado en locación FRAP13. dirige reunión de seguridad con cada una de las empresas aliadas. Divulga Alerta HSE: “Exposición a agua caliente durante cargue de agua de producción.”', 'Charlas de seguridad', 'aprobado', NULL, NULL, NULL, '2026-01-12 00:00:00', '2026-01-12 00:00:00');

-- Reporte 135 - conversaciones (Pedro Rafael Cadena Ordoñez)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(135, 36, NULL, NULL, 'conversaciones', NULL, 'Charlas de seguridad', NULL, '2026-01-09', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'conversacion', 'FRAP13', 'pozos', '', 'Realizó Charla de seguridad con personal aliado en locación FRAP13. dirige reunión de seguridad con cada una de las empresas aliadas. Divulga Alerta HSE: “Fuego Incipiente de estabilizador de energía en oficina.”', 'Charlas de seguridad', 'aprobado', NULL, NULL, NULL, '2026-01-12 00:00:00', '2026-01-12 00:00:00');

-- Reporte 136 - conversaciones (Pedro Rafael Cadena Ordoñez)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(136, 36, NULL, NULL, 'conversaciones', NULL, 'Charlas de seguridad', NULL, '2026-01-10', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'conversacion', 'FRAP13', 'pozos', '', 'Realizó Charla de seguridad con personal aliado en locación FRAP13. dirige reunión de seguridad con cada una de las empresas aliadas. Divulga Alerta HSE: “Ruptura de oreja y grillete durante corrida de Casing.”', 'Charlas de seguridad', 'aprobado', NULL, NULL, NULL, '2026-01-12 00:00:00', '2026-01-12 00:00:00');

-- Reporte 137 - conversaciones (Pedro Rafael Cadena Ordoñez)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(137, 36, NULL, NULL, 'conversaciones', NULL, 'Charlas de seguridad', NULL, '2026-01-11', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'conversacion', 'FRAP13', 'pozos', '', 'Realizó Charla de seguridad con personal aliado en locación FRAP13. dirige reunión de seguridad con cada una de las empresas aliadas. Divulga Alerta HSE: “Caída de herramienta en pie de trabajador.”', 'Charlas de seguridad', 'aprobado', NULL, NULL, NULL, '2026-01-12 00:00:00', '2026-01-12 00:00:00');

-- Reporte 138 - conversaciones (Pedro Rafael Cadena Ordoñez)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(138, 36, NULL, NULL, 'conversaciones', NULL, 'Charlas de seguridad', NULL, '2026-01-12', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'conversacion', 'FRAP13', 'pozos', '', 'Realizó Charla de seguridad con personal aliado en locación FRAP13. dirige reunión de seguridad con cada una de las empresas aliadas. Divulga Alerta HSE: “Incendio en cobertura vegetal en temporada de verano.”', 'Charlas de seguridad', 'aprobado', NULL, NULL, NULL, '2026-01-12 00:00:00', '2026-01-12 00:00:00');

-- Reporte 148 - conversaciones (Carlos Antonio Fontalvo Carrascal)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(148, 106, NULL, NULL, 'conversaciones', NULL, 'GOLPE HOMBRO IZQUIERDO TRABAJADOR', NULL, '2026-01-16', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'conversacion', 'Rig Independence 225', 'pozos', '', 'Momento de seguridad HSE, Tema: GOLPE HOMBRO IZQUIERDO TRABAJADOR empresas involucradas: Independence, Meridian/ECOPETROL, identifico peligros de la actividad, reviso procedimientos, estableció controles operativos y HSE, definió roles y responsabilidades, firmo y valido permisos de trabajo y AR, HSE-F-040 SAS #00024', 'GOLPE HOMBRO IZQUIERDO TRABAJADOR', 'aprobado', NULL, NULL, NULL, '2026-01-23 00:00:00', '2026-01-23 00:00:00');

-- Reporte 149 - conversaciones (Carlos Antonio Fontalvo Carrascal)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(149, 106, NULL, NULL, 'conversaciones', NULL, 'Descenso lento no controlado de bloque viajero', NULL, '2026-01-16', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'conversacion', 'Rig Independence 225', 'pozos', '', 'Momento de Seguridad HSE, Tema: Descenso lento no controlado de bloque viajero, Empresas involucradas: Independence, Meridian/ECOPETROL, Identifico peligros de la actividad, reviso procedimientos, estableció controles operativos y HSE, definió roles y responsabilidades, firmó y validó permisos de trabajo y AR, HSE-F-040 SAS #00024.', 'Descenso lento no controlado de bloque viajero', 'aprobado', NULL, NULL, NULL, '2026-01-23 00:00:00', '2026-01-23 00:00:00');

-- Reporte 150 - conversaciones (Carlos Antonio Fontalvo Carrascal)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(150, 106, NULL, NULL, 'conversaciones', NULL, 'Momento de Seguridad HSE, Tema: Perdida de equilibrio al descender porescalera', NULL, '2026-01-18', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'conversacion', 'Rig Independence 225', 'pozos', '', 'Momento de Seguridad HSE, Tema: Perdida de equilibrio al descender por escalera,Empresas involucradas: Independence, Meridian/ECOPETROL, Identifico peligros de laactividad, reviso procedimientos, estableció controles operativos y HSE, definió roles yresponsabilidades, firmó y validó permisos de trabajo y AR, HSE-F-040 SAS #00024.', 'Momento de Seguridad HSE, Tema: Perdida de equilibrio al descender porescalera', 'aprobado', NULL, NULL, NULL, '2026-01-23 00:00:00', '2026-01-23 00:00:00');

-- Reporte 151 - conversaciones (Carlos Antonio Fontalvo Carrascal)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(151, 106, NULL, NULL, 'conversaciones', NULL, 'Momento de Seguridad HSE, Tema: Pérdida de contención en pozo durante intervención (Evento de Well Control)', NULL, '2026-01-20', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'conversacion', 'Rig Independence 225', 'pozos', '', 'Momento de Seguridad HSE, Tema: Pérdida de contención en pozo durante intervención(Evento de Well Control)', 'Momento de Seguridad HSE, Tema: Pérdida de contención en pozo durante intervención (Evento de Well Control)', 'aprobado', NULL, NULL, NULL, '2026-01-23 00:00:00', '2026-01-23 00:00:00');

-- Reporte 152 - conversaciones (Carlos Antonio Fontalvo Carrascal)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(152, 106, NULL, NULL, 'conversaciones', NULL, 'Momento de Seguridad HSE, Tema: Evento: Incidente de Seguridad Vial, Maniobra de reversa para la salida del área de estacionamiento de la Ambulancia', NULL, '2026-01-21', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'conversacion', 'Rig Independence 225', 'pozos', '', 'Momento de Seguridad HSE, Tema: Evento: Incidente de Seguridad Vial, Maniobra de reversa para la salida del área de estacionamiento de la Ambulancia', 'Momento de Seguridad HSE, Tema: Evento: Incidente de Seguridad Vial, Maniobra de reversa para la salida del área de estacionamiento de la Ambulancia', 'aprobado', NULL, NULL, NULL, '2026-01-23 00:00:00', '2026-01-23 00:00:00');

-- Reporte 153 - conversaciones (Carlos Antonio Fontalvo Carrascal)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(153, 106, NULL, NULL, 'conversaciones', NULL, 'Momento de Seguridad HSE, Tema: Evento: Fuego incipiente de estabilizador deenergía en oficina', NULL, '2026-01-22', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'conversacion', 'Rig Independence 225', 'pozos', '', 'Momento de Seguridad HSE, Tema: Evento: Fuego incipiente de estabilizador de energía en oficina', 'Momento de Seguridad HSE, Tema: Evento: Fuego incipiente de estabilizador deenergía en oficina', 'aprobado', NULL, NULL, NULL, '2026-01-23 00:00:00', '2026-01-23 00:00:00');

-- Reporte 154 - hallazgos (Julio Cesar Romero Arevalo)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(154, 34, NULL, NULL, 'hallazgos', NULL, 'Hallazgo', NULL, '2026-01-12', 'pozos', '', 'acto_inseguro', 'Se observa camioneta reversando a velocidad inadecuada', 'Se comenta con el conductor y este es consiente del peligro en que incurre ajustando su trabajo', 'cerrada', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'aprobado', NULL, NULL, NULL, '2026-01-26 00:00:00', '2026-01-26 00:00:00');

-- Reporte 155 - hallazgos (Julio Cesar Romero Arevalo)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(155, 34, NULL, NULL, 'hallazgos', NULL, 'Hallazgo', NULL, '2026-01-12', 'pozos', '', 'acto_inseguro', 'Se observa camioneta en vía a pozo a alta velocidad.', 'se comunica con el aliado que la contrató y posteriormente con el conductor dejando claro los limites de velocidad y la conciencia del manejo defensivo', 'cerrada', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'aprobado', NULL, NULL, NULL, '2026-01-26 00:00:00', '2026-01-26 00:00:00');

-- Reporte 156 - hallazgos (Julio Cesar Romero Arevalo)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(156, 34, NULL, NULL, 'hallazgos', NULL, 'Hallazgo', NULL, '2026-01-14', 'pozos', '', 'acto_inseguro', 'Se observa zona de operación delimitada con cinta pero sin los avisos completos faltando el de cable en tensión', 'se comunica con la cuadrilla y reajustan el trabajo colocando el letreo apropiado para la labor', 'cerrada', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'aprobado', NULL, NULL, NULL, '2026-01-26 00:00:00', '2026-01-26 00:00:00');

-- Reporte 157 - hallazgos (Julio Cesar Romero Arevalo)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(157, 34, NULL, NULL, 'hallazgos', NULL, 'Rejilla perimetral de contrapozo un poco alta con el potencial de provocar tropiezos y caida', NULL, '2026-01-15', 'pozos', '', 'condicion_insegura', 'Se observa rejilla perimetral de contrapozo un poco alta con el potencial de provocar tropiezos y caidas', 'Se comenta con el personal aliado y se reajusta de manera correcta haciendo el trabajo mas seguro para todos.', 'cerrada', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'aprobado', NULL, NULL, NULL, '2026-02-06 00:00:00', '2026-02-06 00:00:00');

-- Reporte 159 - hallazgos (Julio Cesar Romero Arevalo)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(159, 34, NULL, NULL, 'hallazgos', NULL, 'Se observa persona sin casco en carpa de equipo de presión', NULL, '2026-01-15', 'pozos', '', 'acto_inseguro', 'Se observa persona sin casco en carpa de equipo de presión', 'Se reflexiona sobre el autocuidado a pesar que esta en una carpa se debe utilizar todos los EPP, la persona reacomoda su trabajo.', 'cerrada', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'aprobado', NULL, NULL, NULL, '2026-02-06 00:00:00', '2026-02-06 00:00:00');

-- Reporte 160 - hallazgos (Julio Cesar Romero Arevalo)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(160, 34, NULL, NULL, 'hallazgos', NULL, 'Perrito comiendo restos de almuerzo en zona operativa', NULL, '2026-01-15', 'pozos', '', 'condicion_insegura', 'Se observa perrito comiendo restos de almuerzo en zona operativa', 'Se comenta con el personal que si desean alimentar los animales lo hagan fuera del área de operaciones ya que dichos animales pueden sufrir o causar un accidente, las personas comprenden la relevancia del asunto.', 'cerrada', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'aprobado', NULL, NULL, NULL, '2026-02-06 00:00:00', '2026-02-06 00:00:00');

-- Reporte 161 - conversaciones (Julio Cesar Romero Arevalo)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(161, 34, NULL, NULL, 'conversaciones', NULL, 'Reflexion al observar video', NULL, '2026-01-15', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'reflexion', 'Cusiana T27', 'pozos', '', 'Se realiza reflexión al observar video de accidente de persona que pierde la vida al estar debajo de una carga que se cae cuando estaba suspendida por una grúa y se conversa con el personal sobre lo observado, reflexionando sobre sl autocuidado y el cuidado de los demás en nuestras operaciones día a día, se reflexiona sobre como sufrirían nuestras familias ante una situación de estas y que es posible evitarlas si estamos atentos y cuidándonos.', 'Reflexion al observar video', 'aprobado', NULL, NULL, NULL, '2026-02-06 00:00:00', '2026-02-06 00:00:00');

-- Reporte 162 - conversaciones (Julio Cesar Romero Arevalo)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(162, 34, NULL, NULL, 'conversaciones', NULL, 'Reflexiona sobre la alerta de seguridad', NULL, '2026-01-17', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'reflexion', 'Cusiana T27', 'pozos', '', 'Se reflexiona sobre la alerta de seguridad &quot;Fatalidad Inducción de trabajador durante retiro de bajante (jumper) en actividades de bahía de línea&quot; y se reflexiona sobre la fragilidad del ser humano, podemos perder la vida en un instante y que pasaría con nuestras familias si llegamos a faltar.', 'Reflexiona sobre la alerta de seguridad', 'aprobado', NULL, NULL, NULL, '2026-02-06 00:00:00', '2026-02-06 00:00:00');

-- Reporte 164 - conversaciones (Julio Cesar Romero Arevalo)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(164, 34, NULL, NULL, 'conversaciones', NULL, 'Reflexión sobre la importancia de nuestro trabajo para nuestras familias', NULL, '2026-01-17', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'reflexion', 'CUS TA 27', 'pozos', '', 'Se realiza reflexión sobre la importancia de nuestro trabajo para nuestras familias y del esfuerzo que realizamos estando lejos en días festivos y fechas especiales, animándonos a seguir haciendo las cosas bien para ellos.', 'Reflexión sobre la importancia de nuestro trabajo para nuestras familias', 'aprobado', NULL, NULL, NULL, '2026-02-06 00:00:00', '2026-02-06 00:00:00');

-- Reporte 165 - conversaciones (Esteban Garcia Rojas)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(165, 32, NULL, NULL, 'conversaciones', NULL, 'Verificación de Grúa de 80 ton', NULL, '2026-01-15', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'reflexion', 'Cupiagua T32', 'pozos', '', 'Verificó ubicación de grúa de 80 ton y unidad de SlickLine para evitar interferencias en los movimientos debido al poste pararrayos que está en la vecindad del pozo', 'Verificación de Grúa de 80 ton', 'aprobado', NULL, NULL, NULL, '2026-02-06 00:00:00', '2026-02-06 00:00:00');

-- Reporte 188 - hallazgos (Julio Cesar Romero Arevalo)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(188, 34, NULL, NULL, 'hallazgos', NULL, 'Se observa personal sin equipo de invierno durante lluvia leve', NULL, '2026-02-15', 'pozos', '', 'acto_inseguro', 'Se observa personal sin equipo de invierno durante lluvia leve', 'Se le comenta que aunque la lluvia sea poca se requiere el EPP apropiado para el cuidado de su salud, el personal reacomoda su labor usando dicho equipo.', 'cerrada', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'aprobado', NULL, NULL, NULL, '2026-02-24 00:00:00', '2026-02-24 00:00:00');

-- Reporte 189 - conversaciones (Julio Cesar Romero Arevalo)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(189, 34, NULL, NULL, 'conversaciones', NULL, 'Portacomidas desechables', NULL, '2026-02-16', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'reflexion', 'Floreña T8', 'pozos', '', 'Se observó personal trayendo sus alimentos en portacomidas desechables, se felicita por la acción consiente del cuidado del medio ambiente al no usar desechables', 'Portacomidas desechables', 'aprobado', NULL, NULL, NULL, '2026-02-24 00:00:00', '2026-02-24 00:00:00');

-- Reporte 190 - hallazgos (Julio Cesar Romero Arevalo)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(190, 34, NULL, NULL, 'hallazgos', NULL, 'Poca Iluminación durante Rig Up', NULL, '2026-02-18', 'pozos', '', 'condicion_insegura', 'Se observa área con poca iluminación durante Rig Up de equipos', 'Se conversa con el personal y se concluye que esta mal enfocada, se reacomoda la iluminación continuando con la operación de manera segura.', 'cerrada', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'aprobado', NULL, NULL, NULL, '2026-02-24 00:00:00', '2026-02-24 00:00:00');

-- Reporte 191 - conversaciones (Julio Cesar Romero Arevalo)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(191, 34, NULL, NULL, 'conversaciones', NULL, 'Importancia del alto por la vida', NULL, '2026-02-19', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'reflexion', 'Floreña T7', 'pozos', '', 'Se reflexiona sobre la importancia del alto por la vida y las lecciones aprendidas divulgadas en este, el personal comprende el propósito de este espacio generado para reflexionar sobre el autocuidado y el cuidado de los demás.', 'Importancia del alto por la vida', 'aprobado', NULL, NULL, NULL, '2026-02-24 00:00:00', '2026-02-24 00:00:00');

-- Reporte 192 - conversaciones (Julio Cesar Romero Arevalo)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(192, 34, NULL, NULL, 'conversaciones', NULL, 'contacto directo de excavadora con línea aérea energizada', NULL, '2026-02-19', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'reflexion', 'Floreña T7', 'pozos', '', 'Se reflexiona sobre el evento &quot;contacto directo de excavadora con línea aérea energizada&quot; comprendiendo nuestro entorno de trabajo presenta riesgos que son mitigados al analizarlo detalladamente y a conciencia minimizándolos haciendo una operación segura', 'contacto directo de excavadora con línea aérea energizada', 'aprobado', NULL, NULL, NULL, '2026-02-24 00:00:00', '2026-02-24 00:00:00');

-- Reporte 193 - conversaciones (Julio Cesar Romero Arevalo)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(193, 34, NULL, NULL, 'conversaciones', NULL, 'Se reflexiona sobre el evento &quot;caída de teja en área operativa&quot;', NULL, '2026-02-19', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'reflexion', 'Floreña T7', 'pozos', '', 'Se reflexiona sobre el evento &quot;caída de teja en área operativa&quot; durante el alto por la vida, comprendiendo que no somos ajenos a los accidentes y que estos son evitables.', 'Se reflexiona sobre el evento &quot;caída de teja en área operativa&quot;', 'aprobado', NULL, NULL, NULL, '2026-02-24 00:00:00', '2026-02-24 00:00:00');

-- Reporte 232 - hallazgos (Esteban Garcia Rojas)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(232, 32, NULL, NULL, 'hallazgos', NULL, 'Verificación de Grúa de 80 ton', NULL, '2026-02-27', 'pozos', '', 'accion_mejoramiento', 'Verificó ubicación de grúa de 80 ton y unidad de SlickLine para evitar interferencias en los movimientos debido al poste pararrayos que está en la vecindad del pozo', 'Cambiar Layout para proteger parrarayos', 'cerrada', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'aprobado', NULL, NULL, NULL, '2026-03-05 00:00:00', '2026-03-05 00:00:00');

-- Reporte 233 - hallazgos (Esteban Garcia Rojas)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(233, 32, NULL, NULL, 'hallazgos', NULL, 'Verificación de EPP', NULL, '2026-02-27', 'pozos', '', 'aspecto_positivo', 'Verificó elementos de protección personal de toda la cuadrilla garantizando el uso adecuados', 'EPP correcto para arme', 'cerrada', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'aprobado', NULL, NULL, NULL, '2026-03-05 00:00:00', '2026-03-05 00:00:00');

-- Reporte 234 - hallazgos (Pedro Rafael Cadena Ordoñez)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(234, 36, NULL, NULL, 'hallazgos', NULL, 'Safety Tour', NULL, '2026-03-02', 'pozos', '', 'aspecto_positivo', 'Realizó safety tour al finalizar la intervención en CSK6, se solicita limpieza del well pad por parte del aliado SLB y se realiza la entrega de pozo dejando locación en buenas condiciones de orden y aseo.', 'Ninguna', 'cerrada', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'aprobado', NULL, NULL, NULL, '2026-03-05 00:00:00', '2026-03-05 00:00:00');

-- Reporte 235 - hallazgos (Pedro Rafael Cadena Ordoñez)
INSERT INTO `reportes` (`id`, `id_usuario`, `telefono_contacto`, `correo_contacto`, `tipo_reporte`, `tipo_pqr`, `asunto`, `descripcion_general`, `fecha_evento`, `lugar_hallazgo`, `lugar_hallazgo_otro`, `tipo_hallazgo`, `descripcion_hallazgo`, `recomendaciones`, `estado_condicion`, `grado_criticidad`, `ubicacion_incidente`, `hora_evento`, `tipo_afectacion`, `descripcion_incidente`, `tipo_conversacion`, `sitio_evento_conversacion`, `lugar_hallazgo_conversacion`, `lugar_hallazgo_conversacion_otro`, `descripcion_conversacion`, `asunto_conversacion`, `estado`, `revisado_por`, `comentarios_revision`, `fecha_revision`, `creado_en`, `actualizado_en`) VALUES
(235, 36, NULL, NULL, 'hallazgos', NULL, 'Safety tour al inicio de la intervención', NULL, '2026-03-02', 'pozos', '', 'aspecto_positivo', 'Realizó safety tour al inicio de la intervención en FRAP13, encontrando buenas condiciones de orden y aseo. Verifico el cierre de los hallazgos encontrados en la visita previa y recibe locación por parte de operaciones de superficie.', 'Ninguna', 'cerrada', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, 'aprobado', NULL, NULL, NULL, '2026-03-05 00:00:00', '2026-03-05 00:00:00');

COMMIT;
